### ISSUE TITLE
Hello!

### ISSUE THREAD

**Issue by marchellodev** [Smuzi/BNForestFires#1]
Can you please reach out to me?
`marchellodev@gmail.com`

**Comment by Smuzi** [comment]
Hey, can I help with anything?

**Comment by marchellodev** [comment]
@Smuzi Thank you for replying.

I'm writing to ask you whether you could give us a nickname 'Smuzi'. We are a Ukrainian non-profit organization that develops software for social projects, and we would love to have the domain github.com/smuzi. Here is our GitHub page https://github.com/smuzi-ua, as you can see, we've already done some work, and we are not planning to stop. Right now, we are working on an app for schools that will establish a secure communication channel between schools officials and the students, so pupils can propose some changes or report some misconduct.

This account isn't actively used so I thought maybe you could give us the domain, we would be extremely grateful.

Thank you!

**Comment by marchellodev** [comment]
Hi @Smuzi, any updates?

**Comment by Smuzi** [comment]
Sorry for the delay, I haven't been on lately due to the COVID situation.
About your request, I'm sorry but I'd like to keep the domain since it's a merge of my first and last name. I still use it sometimes and plan on using it in the future, also it has been my username across multiple platforms.

Wish you all the best,
Uzi

**Comment by marchellodev** [comment]
Oh, I see.

Anyways, thank you for the fast response and good luck with your work!
